services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Fasterdot\SymfonyPermissionManager\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    Fasterdot\SymfonyPermissionManager\Twig\PermissionExtension: 
        tags: ['twig.extension']
    